desc: re builds go
triggers:
  - name: ''
    pattens:
      - '**/*.go'
    env:
      DEBUG: '1'
    cmd: |-
      cd /brev && go run ./cmd/brevd/brevd.go serve --dev\
        --default-host=mx0.example.com \
        --http-interface="0.0.0.0" \
        --spool-dir=./spool-data \
        --dkim-domain=example.com \
        --dkim-selector=brev \
        --dkim-key-file=./dkim-test-key/dkim-private.pem \
        --mta-router-default-concurrency=1 \
        --mta-router-server-concurrency=aspmx.l.google.com=2 \
        --mta-retry=3 \
        --mta-retry-duration=4m \
        --metrics-poll

    shell: true
    delay: 100ms
    stop_timeout: 500ms
    signal: KILL
    kill_signal: 'SIGTERM'
watch_paths:
  - .
watch_depth: 10
